name = "worklearn-api"
type = "javascript"
account_id = "5e70260b2fb181962a8cf04f72a4b2ae"
main = "src/index.js"

[env.production]
vars = { ENVIRONMENT = "production" }

[[d1_databases]]
binding = "DB"
database_name = "worklearn"
database_id = "worklearn-db"

[[kv_namespaces]]
binding = "CACHE"
id = "worklearn-cache"

[[r2_buckets]]
binding = "R2"
bucket_name = "worklearn"

[build]
command = "npm install"

routes = [
  { pattern = "career.jokerow.com/api/*", zone_name = "jokerow.com" }
]
